version: '3.8'

services:
  api:
    build: ./
    command: gunicorn --bind 0.0.0.0:5000 --workers 1 --threads 8 main:app
    volumes:
      - ./:/usr/src/app/
      - type: bind
        source: ./data/voynich-manuscript-classifications.csv
        target: /usr/src/app/data/voynich-manuscript-classifications.csv
        read_only: true
    ports:
      - 5000:5000
    env_file:
      - .env
  db:
      image: postgres:14-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=voynich_admin
        - POSTGRES_PASSWORD=voynich_admin
        - POSTGRES_DB=voynich_dev

volumes:
  postgres_data: