version: '3.8'

services:
  api:
    build: ./
    command: python app.py run -h 0.0.0.0
    volumes:
      - ./:/usr/src/app/
      - type: bind
        source: ./data/voynich-manuscript-classifications.csv
        target: /usr/src/app/data/voynich-manuscript-classifications.csv
        read_only: true
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
  db:
      image: postgres:14-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=hello_flask
        - POSTGRES_PASSWORD=hello_flask
        - POSTGRES_DB=hello_flask_dev

volumes:
  postgres_data: